#!/bin/bash
{
    curl -s https://www.cloudflare.com/ips-v4 | sed 's|^|set_real_ip_from |;s|$|;|'
    echo
    curl -s https://www.cloudflare.com/ips-v6 | sed 's|^|set_real_ip_from |;s|$|;|'
    echo
    echo "real_ip_header X-Forwarded-For;"
} | tr -s '\n' '\n' > /etc/nginx/conf.d/cloudflare.conf

nginx -t && systemctl reload nginx
