#!/bin/bash
# Replace repo in /etc/apt/sources.list
sed -i "s|jp|vn|g" /etc/apt/sources.list

# Update package list
apt update

# Upgrade installed packages
apt upgrade -y

# Remove UFW (Uncomplicated Firewall)
apt remove ufw -y

# Remove UFW configurations
rm -rf /etc/ufw

# Flush and delete UFW-related iptables rules
for ufw in $(iptables -L | grep 'Chain ufw' | awk '{ print $2 }'); do
    iptables -F $ufw
done

for ufw in $(iptables -L | grep 'Chain ufw' | awk '{ print $2 }'); do
    iptables -D INPUT -j $ufw
    iptables -D FORWARD -j $ufw
    iptables -D OUTPUT -j $ufw
done

for ufw in $(iptables -L | grep 'Chain ufw' | awk '{ print $2 }'); do
    iptables -X $ufw
done

# Download FastPanel installation script
wget http://repo.fastpanel.direct/install_fastpanel.sh

# Check the Ubuntu version
if [ $(lsb_release -rs) == "20.04" ]; then
    echo "Ubuntu 20.04 is detected."
    bash install_fastpanel.sh -m mariadb10.5
elif [ $(lsb_release -rs) == "22.04" ]; then
    echo "Ubuntu 22.04 is detected."
    bash install_fastpanel.sh
else
    echo "Unsupported Ubuntu version. This script supports Ubuntu 20.04 and 22.04 only."
    exit 1
fi

# Remove file FastPanel installation script
rm -f install_fastpanel.sh
