#!/bin/bash

# Remove UFW if installed
command -v ufw &> /dev/null && apt remove ufw -y

# Set up default iptables rules
mkdir -p /etc/iptables
cat << EOT > /etc/iptables/rules.v4
*mangle
:PREROUTING ACCEPT [109:169662]
:INPUT ACCEPT [101:168958]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [105:237695]
:POSTROUTING ACCEPT [105:237695]
COMMIT
*raw
:PREROUTING ACCEPT [109:169662]
:OUTPUT ACCEPT [105:237695]
COMMIT
*filter
:INPUT ACCEPT [101:168958]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [105:237695]
COMMIT
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
EOT

# Clean up old files
rm -f /etc/iptables/rules.v6
rm -rf /etc/ufw

# Restore iptables rules
iptables-restore < /etc/iptables/rules.v4
